blueprints/calendar_routes.py
from flask import session, request, render_template, abort
from flask import request, Blueprint
from tt_calendar.models import *
from tt_calendar import utils

from datetime import datetime, timezone, timedelta

import json, logging
import time

cal = Blueprint('cal_bp', __name__)



# ======================================
# ======== Calendar Endpoints ==========
# ======================================

@cal.route('/', defaults={'view_type': 'regular'}, methods=['GET'])
@cal.route('/<string:view_type>', methods=['GET'])
def view(view_type):
    if view_type not in ['public', 'regular', 'template']:
        abort(404)

    user = {}
    user['name'] = session.get('username', None)
    user['is_member'] = session.get('is_member', None)
    user['member'] = "Ja" if session.get('is_member', None) else "Nein"
    user['beirat'] = "Ja" if session.get('is_beirat', None) else "Nein"
    user['vorstand'] = "Ja" if session.get('is_vorstand', None) else "Nein"
    user['admin'] = "Ja" if session.get('is_admin', None) else "Nein"
    user['id'] = session.get('user_id', None)

    logging.info(f"Calendar opened by {user['name']}, {user['is_member']=}")

    date_str = request.args.get('date', datetime.utcnow().strftime('%Y-%m-%d'))
    date = datetime.strptime(date_str, '%Y-%m-%d').date()

    rooms = Room.query.order_by(Room.id).all()

    return render_template('view.html', view_type=view_type, date=date, user=user, rooms=rooms)



from blueprints.api_routes import prepare_reservations_for_jinja

#This takes no argument since they come from an html form.
@cal.route('/fetch/day')
def fetch_day():
    date_str = request.args.get('date', datetime.utcnow().strftime('%Y-%m-%d'))
    date = datetime.strptime(date_str, '%Y-%m-%d').date()
    view_type = request.args.get('view_type', 'public')
    room_id = request.args.get('room_id', type=int)

    if not session.get("is_member"):
        view_type = "public"

    reservations = prepare_reservations_for_jinja(view_type, date_str, date_str, room_id=room_id)
    tables = Table.query.filter_by(room_id=room_id).order_by(Table.id).all() # Table ID must be ordered
    event_types = EventType.query.all()
    return render_template('partials/calendar_content.html', 
                           date=date, 
                           tables=tables, 
                           event_types=event_types,
                           reservations=reservations)


#This takes no argument since they come from an html form.
@cal.route('/fetch/month')
def fetch_month():
    t0 = time.perf_counter()
    date_str = request.args.get('date', datetime.utcnow().strftime('%Y-%m-%d'))
    date = datetime.strptime(date_str, '%Y-%m-%d').date()
    view_type = request.args.get('view_type', 'public')
    room_id = request.args.get('room_id', type=int)

    if not session.get("is_member"):
        view_type = "public"

    week_start, week_end = utils.get_end_days_of_week(date)
    date_range, first_date_str, last_date_str = utils.get_end_days_of_month(date)
    reservations = prepare_reservations_for_jinja(view_type, first_date_str, last_date_str, room_id=room_id)
    tables = Table.query.filter_by(room_id=room_id).order_by(Table.id).all() # Table ID must be ordered
    event_types = EventType.query.all()

    occupancy_by_day = utils.get_occupancy_by_day(reservations, tables)

    today = datetime.now(timezone.utc).date()
    t1 = time.perf_counter()
    print(f"[prep] month total:           {(t1 - t0)*1000:.1f}ms")
    return render_template('partials/month_content.html', 
                           date=date, 
                           tables=tables, 
                           event_types=event_types,
                           reservations=reservations,
                           date_list=list(date_range),
                           week_start=week_start,
                           week_end=week_end,
                           occupancy_by_day=json.dumps(occupancy_by_day),
                           today=today)



@cal.route('/fetch/reservation/<string:event_id>')
def reservation_popup(event_id):
    # Fetch reservation and related data from the database
    reservation = Reservation.query.filter_by(event_id=event_id).first()

    # If no reservation is found, return a 404 error
    if reservation is None:
        abort(404)

    # Get only the needed data
    reservation_data = {
        'id': reservation.id,
        'user_name': reservation.user.username,
        'user_id': reservation.user.id,
        'event_id': reservation.event_id,
        'template_id': reservation.associated_event.template_id,
        'date': reservation.associated_event.start_time.strftime('%d.%m.%Y'),
        'start_time': reservation.associated_event.start_time.strftime('%H:%M'),
        'end_time': reservation.associated_event.end_time.strftime('%H:%M'),
        'game_category': reservation.associated_event.game_category.name,
        'name': reservation.associated_event.name,
        'description': reservation.associated_event.description,
        'time_created': reservation.associated_event.time_created.strftime('%d.%m.%Y %H:%M'),
        'time_updated': reservation.associated_event.time_updated.strftime('%d.%m.%Y %H:%M') if reservation.associated_event.time_updated else None,
        'publicity': reservation.associated_event.publicity.name,
        'discord_link': reservation.associated_event.get_discord_message_url()
    }

    if session.get('is_member', False):
        reservation_data['attendees'] = ', '.join([attendee.username for attendee in reservation.associated_event.attendees])
    else:
        reservation_data['attendees'] = len(reservation.associated_event.attendees)

    table = Table.query.get(reservation.table_id)
    event_type = EventType.query.get(reservation.associated_event.event_type_id)
    related_tables = Table.query.join(Reservation, Reservation.table_id == Table.id)\
                                .filter(Reservation.event_id == event_id)\
                                .all()
    relatedTablesInfo = ', '.join(table.name for table in related_tables)

    # Render the popup template with the fetched data
    return render_template('partials/calendar_reservation_popup.html', 
                           reservation=reservation_data, 
                           event_type=event_type, 
                           relatedTablesInfo=relatedTablesInfo)

@cal.route('/shortcuts')
def popup_shortcuts():
    return render_template('partials/popup_shortcuts.html')

@cal.route('/tutorial')
def popup_tutorial():
    return render_template('partials/popup_tutorial.html')


@cal.route('/calendar/popup-userevents')
def popup_userevents():
    user = User.query.get(session['user_id'])
    assert user

    now = datetime.now(pytz.timezone('Europe/Berlin'))
    week_ago = now - timedelta(days=1)
    week_later = now + timedelta(days=28)

    events = Event.query.filter(
        Event.start_time.between(week_ago, week_later),
        Event.deleted == False,
    ).filter(
        (Event.user_id == user.id) | 
        (Event.attendees.any(id=user.id))
    ).order_by(Event.start_time).all()

    # Fetch own templates
    templates = Event.get_template_events().filter(
        Event.user_id == user.id
    )

    return render_template('partials/popup_userevents.html', events=events, templates=templates)


@cal.route('/calendar/popup-useridcard')
def popup_useridcard():
    user = User.query.get(session['user_id'])
    assert user

    now = datetime.now(pytz.timezone('Europe/Berlin'))

    return render_template('partials/popup_useridcard.html', user=user)

blueprints/ics_routes.py
from flask import request, Blueprint, abort, send_file
from tt_calendar.models import *

from ics import Calendar, Event as ICSEvent
from io import BytesIO
import pytz

ics = Blueprint('ics_bp', __name__)

# HELPER FUNCTIONS

def create_ics_event_from_event(event):
    ics_event = ICSEvent()
    ics_event.name = event.name
    ics_event.begin = event.start_time
    ics_event.end = event.end_time
    ics_event.uid = f"{event.id}@3TH"
    ics_event.description = event.description
    if event.get_discord_message_url():
        ics_event.location = f"https://{event.get_discord_message_url()}"
    ics_event.created = event.time_created
    return ics_event

# ROUTES

@ics.route('/event/<string:event_id>', methods=['GET'])
def get_event_ics(event_id):
    # Fetch event by ID
    given_event = Event.query.get(event_id)
    if not given_event or given_event.deleted:
        abort(404, description="Event not found")

    calendar = Calendar()

    # Determine if the event is part of a recurring series
    if given_event.template_id:
        events = Event.get_events_linked_to_template(given_event.template_id).order_by(Event.start_time).all()
    else:
        events = [given_event]


    for event in events:
        calendar.events.add(create_ics_event_from_event(event))

    calendar_bytes = BytesIO(calendar.serialize().encode('utf-8'))

    response = send_file(calendar_bytes, as_attachment=True, download_name=f"{given_event.name}.ics", mimetype='text/calendar')
    response.headers['Content-Disposition'] = f'attachment; filename="{given_event.name}.ics"'
    return response


@ics.route('/calendar/all', methods=['GET'])
def get_all_events_ics():
    calendar = Calendar()

    events = Event.get_regular_events().order_by(Event.start_time).all()
    for event in events:
        calendar.events.add(create_ics_event_from_event(event))

    calendar_bytes = BytesIO(calendar.serialize().encode('utf-8'))
    return send_file(calendar_bytes, as_attachment=True, download_name="calendar_all.ics", mimetype='text/calendar')


@ics.route('/calendar/public', methods=['GET'])
def get_public_events_ics():
    calendar = Calendar()

    public_events = Event.get_regular_events().filter(Event.publicity_id == 1).order_by(Event.start_time).all()
    for event in public_events:
        calendar.events.add(create_ics_event_from_event(event))

    calendar_bytes = BytesIO(calendar.serialize().encode('utf-8'))
    return send_file(calendar_bytes, as_attachment=True, download_name="calendar_public.ics", mimetype='text/calendar')


@ics.route('/calendar/gamecategory/<int:gamecategory_id>', methods=['GET'])
def get_gamecategory_events_ics(gamecategory_id):
    calendar = Calendar()

    events = Event.get_regular_events() \
        .filter(Event.game_category_id == gamecategory_id) \
        .order_by(Event.start_time).all()

    for event in events:
        calendar.events.add(create_ics_event_from_event(event))

    calendar_bytes = BytesIO(calendar.serialize().encode('utf-8'))
    return send_file(calendar_bytes, as_attachment=True, download_name=f"calendar_gamecategory_{gamecategory_id}.ics", mimetype='text/calendar')

templates/partials/calendar_content.html
{% set rowSizes = tables | map(attribute='capacity') | join('fr ') + 'fr' %}

{% set eventTypeColorMap = {} %}
{% for event_type in event_types %}
    {% set _ = eventTypeColorMap.update({ event_type.id: event_type.color }) %}
{% endfor %}

{% set is_weekend = date.weekday() in [5, 6] %}  {# 5 is Saturday, 6 is Sunday #}

{% set lowest_table_id = tables[0].id %} {# used for multiple rooms so the grid row funcs work #}




{% include 'partials/calendar_scale.html' %}

<div id="calendar" 
    class="calendar"
    style="grid-template-rows: {{ rowSizes }};">

    <!-- Table Headers -->
    {% for table in tables %}
        <div class="table-header" 
             style="grid-row: {{ loop.index  }} / {{ loop.index + 1 }};
                {% if table.type == 'RPG' %}
                    background-color: {{ 'var(--accent-color-light)' if not is_weekend else '#cdf' }}
                {% endif %}"
             data-table-id="{{ table.id }}"
             data-table-name="{{ table.name }}"
             data-table-info="{{ table.name }}"
             data-hover-info="Tisch: {{ table.name }} - Kapazität: {{ table.capacity }}">
        </div>
        <div class = "hover-reservation"
            style="grid-row: {{ loop.index  }} / {{ loop.index + 1 }};">
        </div>
    {% endfor %}

    <!-- Reservations -->
    {% for reservation in reservations %}

        <div class="reservation" 
             style="background-color: {{ eventTypeColorMap.get(reservation.event_type_id, '#3788d8') }};
                grid-row: {{ reservation.table_id - lowest_table_id + 1}} / {{ reservation.table_id - lowest_table_id + 2}};"
             data-event-id="{{ reservation.event_id }}"
             data-table-id="{{ reservation.table_id }}"
             data-lowest-table-id="{{ lowest_table_id }}"
             data-reservation-start="{{ reservation.start_time }}"
             data-reservation-end="{{ reservation.end_time }}"
             data-is-marked="{{ reservation.is_marked }}"
             data-is-template="{{ reservation.is_template }}"
             data-event-table-count="{{ reservation.event_table_count }}"
             hx-get="{{ url_for('cal_bp.reservation_popup', event_id=reservation.event_id) }}"
             hx-target="body"
             hx-swap="beforeend">

            <div class="reservation-wrapper">
                <b class="reservation-info-name">{{ reservation.name }}</b>
                <i class="reservation-info-time"></i>
                <span class="reservation-info-attendees">{{ reservation.attendee_count }} Personen</span>
                <span class="reservation-info-publicity">{{ reservation.publicity }}</span>
                
                {% if reservation.game_category_icon %}
                    <img src="data:image/svg+xml;base64,{{ reservation.game_category_icon }}" 
                         alt="Category Icon" 
                         class="reservation-info-icon"
                         style="height: 20px; width: 20px;"
                         title="{{ reservation.game_category }}">
                {% endif %}
            </div>
        </div>
    {% endfor %}

    <div class="side-nav prev-day"></div>
    <div class="side-nav next-day"></div>
</div>

{% include 'partials/calendar_scale.html' %}

templates/partials/calendar_reservation_popup.html
<div class="popup-overlay" style="inset: 0;
                                margin: 0;
                                position: fixed;
                                backdrop-filter: blur(3px);">
    <div class="reservation-popup">
        <div class="popup-content">
            <!-- TODO Might not be datetime sensitive?  -->
            {# {% set date = reservation.start_time.strftime('%d.%m.%Y') %}
            {% set start_time = reservation.start_time.strftime('%H:%M') %}
            {% set end_time = reservation.end_time.strftime('%H:%M') %} #}

            <!-- Reservation Information -->
            <div class="popup-label">{{ reservation.date }}</div>
            <div class="popup-heading">{{ reservation.name }}</div>

            <div class="popup-label">{{ event_type.name }}</div>
            <div class="popup-value">{{ reservation.publicity }}</div>

            <div class="popup-label">{{ reservation.game_category }}</div>
            <div class="popup-value">{{ reservation.start_time }} Uhr bis {{ reservation.end_time }} Uhr</div>

            <div class="popup-label">Tische:</div>
            <div class="popup-value">{{ relatedTablesInfo }}</div>

            <div class="popup-label">Teilnehmende:</div>
            <div class="popup-value">{% if session.get('is_member') %}{{ reservation.attendees or "Keine Teilnehmer" }}{% else %}{{ reservation.attendees|length if reservation.attendees else "0" }}{% endif %}</div>


            <div class="popup-label">Discord:</div>
            <div class="popup-value" style="white-space: initial">
                App: discord://{{ reservation.discord_link }} -
                Web: https://{{ reservation.discord_link }}
            </div>


            <div class="popup-label">Beschreibung:</div>
            <div style="max-height: 8rem;"
                 class="popup-value">{{ reservation.description }}</div>
        </div>

        <!-- Footer -->
        <div class="popup-footer">
            <div class="creator-info">
                <span>{{ reservation.user_name }}</span>
                <span style="text-align: right;">{{ "Editiert am " + reservation.time_updated if reservation.time_updated else "Erstellt am " + reservation.time_created }}</span>
            </div>
            <div class="popup-footer-buttons">
                

                <script src="https://unpkg.com/htmx.org/dist/ext/json-enc.js"></script>
                <button 
                    class="edit-popup" 
                    hx-post="/api/attendance"
                    hx-ext="json-enc"
                    hx-vals='{
                        "discord_user_id": "{{ session.discord_user_id }}",
                        "username": "{{ session.username }}",
                        "event_id": "{{ reservation.event_id }}",
                        "action": "attend"
                    }'
                    hx-headers='{"Content-Type": "application/json"}'
                    hx-trigger="click"
                    hx-swap="none">
                    Ich bin dabei!
                </button>

                <button 
                    class="edit-popup" 
                    hx-post="/api/attendance"
                    hx-ext="json-enc"
                    hx-vals='{
                        "discord_user_id": "{{ session.discord_user_id }}",
                        "username": "{{ session.username }}",
                        "event_id": "{{ reservation.event_id }}",
                        "action": "not_attend"
                    }'
                    hx-headers='{"Content-Type": "application/json"}'
                    hx-trigger="click"
                    hx-swap="none">
                    Ich kann nicht.
                </button>

                <button class="edit-popup" onclick="window.location.href='{{ url_for('ics_bp.get_event_ics', event_id=reservation.event_id) }}'">ICS Laden</button>
                
            </div>
            <br>
            <div class="popup-footer-buttons" style="margin-top: 1rem;">
                {% if reservation.user_id == session.user_id or session.is_admin or session.is_vorstand %}
                    <button class="edit-popup" onclick="window.location.href='{{ url_for('event_bp.edit_event', event_id=reservation.event_id) }}'">Editieren</button>
                    {% if reservation.template_id %}
                        <button class="edit-popup" onclick="window.location.href='{{ url_for('template_bp.edit_template', event_id=reservation.template_id) }}'">
                            Vorlage bearbeiten
                        </button>
                    {% endif %}
                {% endif %}
                <button class="close-popup" onclick="this.closest('.popup-overlay').remove()">Schließen</button>
            </div>
        </div>
    </div>
</div>
<script>
document.addEventListener('click', function(event) {
    const overlay = document.querySelector('.popup-overlay');
    const popup = document.querySelector('.reservation-popup');

    // Check if the click is outside the popup
    if (overlay && popup && !popup.contains(event.target)) {
        overlay.remove();
    }
});

document.addEventListener('keydown', e => e.key === 'Escape' && document.querySelector('.popup-overlay')?.remove());

</script>

templates/partials/calendar_scale.html
<div class="time-scale">
    <span class="time-label" data-hour="8">08:00</span>
    <span class="time-label uneven-hour" data-hour="9">09:00</span>
    <span class="time-label" data-hour="10">10:00</span>
    <span class="time-label uneven-hour" data-hour="11">11:00</span>
    <span class="time-label" data-hour="12">12:00</span>
    <span class="time-label uneven-hour" data-hour="13">13:00</span>
    <span class="time-label" data-hour="14">14:00</span>
    <span class="time-label uneven-hour" data-hour="15">15:00</span>
    <span class="time-label" data-hour="16">16:00</span>
    <span class="time-label uneven-hour" data-hour="17">17:00</span>
    <span class="time-label" data-hour="18">18:00</span>
    <span class="time-label uneven-hour" data-hour="19">19:00</span>
    <span class="time-label" data-hour="20">20:00</span>
    <span class="time-label uneven-hour" data-hour="21">21:00</span>
    <span class="time-label" data-hour="22">22:00</span>
    <span class="time-label uneven-hour" data-hour="23">23:00</span>
    <span class="time-label" data-hour="24">24:00</span>


    <div class="side-nav prev-time"></div>
    <div class="side-nav next-time"></div>
</div>

templates/partials/login_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login erfolgreich</title>
    <style>
        body {
            background: #f5f5f5;
            font-family: Arial, sans-serif;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        h2 {
            color: #4CAF50;
            margin-bottom: 20px;
            text-align: center;
        }
        .spinner {
            border: 6px solid #ddd;
            border-top: 6px solid #4CAF50;
            border-radius: 50%;
            width: 40px;
            height: 40px;
            animation: spin 1s linear infinite;
            margin-bottom: 20px;
        }
        @keyframes spin {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
        }
        p {
            color: #555;
            font-size: 1rem;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="spinner"></div>
    <h2>Login erfolgreich!</h2>
    <p>Weiterleitung erfolgt...</p>

    <script>
        if (window.opener) {
            window.opener.postMessage('login_success', window.location.origin);
            setTimeout(() => {
                window.close();
            }, 1000);
        } else {
            window.location.href = '/';
        }
    </script>
</body>
</html>

templates/partials/month_content.html
{% set eventTypeColorMap = {} %}
{% for event_type in event_types %}
    {% set _ = eventTypeColorMap.update({ event_type.id: event_type.color }) %}
{% endfor %}

<script>
    occupancyByDay = JSON.parse('{{ occupancy_by_day | safe }}');
    document.dispatchEvent(new CustomEvent('newMonthLoaded'));
</script>


<div class="day-header">Mo</div>
<div class="day-header">Di</div>
<div class="day-header">Mi</div>
<div class="day-header">Do</div>
<div class="day-header">Fr</div>
<div class="day-header">Sa</div>
<div class="day-header">So</div>


{% for day in date_list %}
    <div class="day {% if day == today %}today{% elif day < today %}past{% endif %}" data-date="{{ day.strftime('%Y-%m-%d') }}">
        <div class="day-heading">
            <span class="mobile-weekday">{{ day.strftime('%a') }}</span>
            <span class="day-number">{{ day.day }}</span>
            <div class="heat-bar"></div>
        </div>
        <div class="day-events">
            {% for reservation in reservations %}
                {% if reservation.date == day %}
                    <div class="event" 
                        style="background-color: {{ eventTypeColorMap.get(reservation.event_type_id, '#3788d8') }};"
                        data-event-id="{{ reservation.event_id }}"
                        data-is-marked="{{ reservation.is_marked }}"
                        data-is-template="{{ reservation.is_template }}">
                        
                        <span class="event-name">{{ reservation['name'] }}</span>
                        <span class="event-time">{{ reservation['start_time_str'] }} - {{ reservation['end_time_str'] }}</span>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endfor %}

templates/partials/popup_floorplan.html
<style>
    .floor-wrapper {
        aspect-ratio: 26 / 31;
        width: 100%; /* or set a max-width */
      }

    .floorgrid-container {
        display: grid;
        grid-template-columns: repeat(26, 1fr);
        grid-template-rows: repeat(31, 1fr);
        background-color: white;
        height: 100%;
        width: 100%;
    }

    .wall {
        background-color: #333;
    }

    .door {
        background-color: #aaa;
    }

    .tabled {
        background-color: orange;
        display: flex;
        justify-content: center;
        align-items: center;
        font-size: 1rem;
        font-weight: bold;
        border: 0.15rem solid black;
        border-radius: .5rem;
        box-shadow: 1px 1px 8px gray;
    }

    .table {
        padding: 10px;
        font-size: 0.9rem;
        cursor: pointer;
        border: 1px solid #ccc;
        background-color: #f9f9f9;
        border-radius: 5px;
        /* height: 3rem; */
        transition: background-color 0.1s;
        color: black;
    }

    .table:hover {
        background-color: #ddd;
    }

    .door {
        background-color: #aaa;
        display: flex;
        justify-content: center;
        align-items: center;
        font-size: 10px;
        color: white;
    }

    .wc {
        background-color: #fff;
        display: flex;
        justify-content: center;
        align-items: center;
        font-weight: bold;
        color: black;
    }
</style>
<div class="popup-overlay" style="inset: 0; margin: 0; position: fixed; backdrop-filter: blur(3px);">
    <div class="floor-wrapper">
        <div class="floorgrid-container">
            <!-- Walls -->
            <div class="wall" style="grid-column: 1 / 2; grid-row: 1 / 30;"></div>
            <div class="wall" style="grid-column: 1 / 22; grid-row: 1 / 2;"></div>
            <div class="wall" style="grid-column: 25 / 27; grid-row: 1 / 2;"></div>
            <div class="wall" style="grid-column: 2 / 9; grid-row: 2 / 4;"></div>
            <div class="wall" style="grid-column: 13 / 14; grid-row: 2 / 6"></div>
            <div class="wall" style="grid-column: 2 / 4; grid-row: 8 / 9;"></div>
            <div class="wall" style="grid-column: 7 / 9; grid-row: 8 / 9;"></div>
            <div class="wall" style="grid-column: 8 / 9; grid-row: 9 / 12;"></div>
            <div class="wall" style="grid-column: 2 / 3; grid-row: 13 / 16;"></div>
            <div class="wall" style="grid-column: 2 / 14; grid-row: 12 / 13;"></div>
            <div class="wall" style="grid-column: 13 / 14; grid-row: 9 / 12;"></div>
            <div class="wall" style="grid-column: 13 / 15; grid-row: 16 / 18;"></div>
            <div class="wall" style="grid-column: 8 / 9; grid-row: 9 / 12;"></div>
            <div class="wall" style="grid-column: 26 / 27; grid-row: 1 / 30;"></div>
            <div class="wall" style="grid-column: 24 / 26; grid-row: 14 / 17;"></div>
            <div class="wall" style="grid-column: 1 / 11; grid-row: 30 / 31;"></div>
            <div class="wall" style="grid-column: 17 / 27; grid-row: 30 / 31;"></div>

            <!-- Doors-->
            <div class="door" style="grid-column: 22 / 25; grid-row: 1 / 2;">Hoftür</div>
            <div class="door" style="grid-column: 4 / 7; grid-row: 8 / 9;">WC Tür</div>
            <div class="door" style="grid-column: 2 / 4; grid-row: 4 / 8;">Küche</div>
            <div class="door" style="grid-column: 3 / 13; grid-row: 13 / 15;">Regale</div>
            <div class="door" style="grid-column: 2 / 3; grid-row: 16 / 23;">Regal</div>
            <div class="door" style="grid-column: 15 / 17; grid-row: 27 / 28;">Hochtisch</div>

            <div class="door" style="grid-column: 11 / 17; grid-row: 28 / 30;">Eingang</div>

            <!-- WC -->
            <div class="wc" style="grid-column: 2 / 8; grid-row: 9 / 12;">WC</div>

            <!-- Tables -->
            <div class="table table-button" style="grid-column: 4 / span 4; grid-row: 23 / span 6;">Tisch 1</div>
            <div class="table table-button" style="grid-column: 4 / span 6; grid-row: 16 / span 4;">Tisch 2</div>
            <div class="table table-button" style="grid-column: 12 / span 6; grid-row: 18 / span 4;">Tisch 3</div>
            <div class="table table-button" style="grid-column: 19 / span 6; grid-row: 25 / span 4;">Tisch 4</div>
            <div class="table table-button" style="grid-column: 20 / span 6; grid-row: 18 / span 4;">Tisch 5</div>
            <div class="table table-button" style="grid-column: 20 / span 3; grid-row: 10 / span 4;">Tisch 6.1</div>
            <div class="table table-button" style="grid-column: 23 / span 3; grid-row: 10 / span 4;">Tisch 6.2</div>
            <div class="table table-button" style="grid-column: 17 / span 6; grid-row: 4 / span 4;">Tisch 7</div>
            <div class="table table-button" style="grid-column: 14 / span 3; grid-row: 12 / span 4;">Tisch 7.5</div>

        </div>
    </div>
</div>

templates/partials/popup_tutorial.html
<div class="popup-overlay" style="inset: 0; margin: 0; position: fixed; backdrop-filter: blur(3px);">
    <div class="reservation-popup">
        <div class="popup-content">
            <div class="popup-heading">⚡ Tastenkürzel</div>
            <div class="popup-value">test</div>

            <div class="popup-label">Mehr Info</div>
            <div class="popup-value">Tolle Info</div>



        </div>
        <div class="popup-footer">
            <div class="popup-footer-buttons">
                <button class="edit-popup"
                    onclick="this.closest('.popup-overlay').remove(); 
                            htmx.ajax('GET', '/calendar/shortcuts', { target: 'body', swap: 'beforeend' });">
                    Tastenkürzel
                </button>

                <button class="close-popup" 
                    onclick="this.closest('.popup-overlay').remove()">
                    Schließen
                </button>
                
                

            </div>
        </div>
    </div>
</div>

<script>
document.addEventListener('click', function(event) {
    const overlay = document.querySelector('.popup-overlay');
    const popup = document.querySelector('.reservation-popup');

    if (overlay && popup && !popup.contains(event.target)) {
        overlay.remove();
    }
});

document.addEventListener('keydown', e => {
    if (e.key === 'Escape') {
        document.querySelector('.popup-overlay')?.remove();
    }
});
</script>